<!-- Generated by Gemini -->
<!-- not taking credit for something i didnt generate -->

<script setup lang="ts">
import { computed } from 'vue'

// 1. Define our accepted props
const props = withDefaults(defineProps<{
    variant?: 'solid' | 'outline' | 'ghost'
    color?: 'primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | (string & {})
    // NEW: Added size options
    size?: 'small' | 'medium' | 'large'
}>(), {
    variant: 'solid',
    color: 'primary',
    size: 'medium' // Default to medium so it doesn't break existing usage
})

// 2. Create a dictionary of semantic colors
const colorMap: Record<string, string> = {
    primary: '#3b82f6',   // Blue
    secondary: '#6b7280', // Gray
    success: '#10b981',   // Green
    danger: '#ef4444',    // Red
    warning: '#f59e0b',   // Orange/Yellow
    info: '#0ea5e9',      // Light Blue
}

// 3. Compute the final color. 
const resolvedColor = computed(() => colorMap[props.color] || props.color)
</script>

<template>
    <button :class="['app-button', variant, size]" :style="{ '--btn-color': resolvedColor }">
        <slot />
    </button>
</template>

<style scoped>
.app-button {
    border-radius: 6px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
    border: 2px solid var(--btn-color);
    /* Removed static padding and font-size from here so sizes can govern them */
}

/* --- SIZES (New!) --- */
.app-button.small {
    padding: 6px 12px;
    font-size: 12px;
}

.app-button.medium {
    padding: 10px 20px;
    font-size: 14px;
}

.app-button.large {
    padding: 14px 28px;
    font-size: 16px;
}

/* --- SOLID VARIANT --- */
.app-button.solid {
    background-color: var(--btn-color);
    color: #ffffff;
}

.app-button.solid:hover {
    opacity: 0.85;
}

/* --- OUTLINE VARIANT --- */
.app-button.outline {
    background-color: transparent;
    color: var(--btn-color);
}

.app-button.outline:hover {
    background-color: var(--btn-color);
    color: #ffffff;
}

/* --- GHOST VARIANT --- */
.app-button.ghost {
    background-color: transparent;
    color: var(--btn-color);
    border-color: transparent;
}

.app-button.ghost:hover {
    background-color: color-mix(in srgb, var(--btn-color) 15%, transparent);
}
</style>